// ===== Bảng tên viết tắt -> id trang bị (Data Dragon 16.18.1 / bản 26.18) =====
const I = {
  // Phép thuật
  rab:3089, vs:3135, cry:3137, lud:6655, bft:2503, lia:6653, rylai:3116, zho:3157, banshee:3102,
  shad:4645, storm:4646, hor:4628, cos:4629, rift:4633, nash:3115, lich:3100, arch:3003, rod:6657,
  mal:3118, morel:3165, blc:8010, belt:3152, imp:4005, dd:2510, chrono:2522, gun:3146, statik:3087,
  guin:3124, wit:3091,
  // Hỗ trợ
  shur:2065, red:3107, mik:3222, sol:3190, vow:3109, zeke:3050, bandle:2524, fwater:6616, moon:6617,
  helia:6620, dawn:6621, cens:3504,
  // Chống chịu
  sun:3068, hol:6664, heart:3084, warm:3083, thorn:3075, fon:4401, sv:3065, ran:3143, jak:6665,
  abyss:8020, kaen:2504, und:2502, fh:3110, winter:3119, ghand:6662, dms:3742, prim:2525,
  // Vật lý
  ie:3031, yun:3032, mr:3033, ldr:3036, atma:3039, pd:3046, ster:3053, bc:3071, bt:3072, hex:3073,
  rav:3074, tri:3078, runaan:3085, rfc:3094, sr:3095, merc:3139, ghost:3142, botrk:3153, maw:3156,
  shojin:3161, umb:3179, hull:3181, term:3302, reap:3508, titan:3748, edge:3814, opp:4004, dance:6333,
  chem:6609, sky:6610, strid:6631, kraken:6672, sbow:6673, navori:6675, col:6676, ecl:6692, sery:6694,
  serp:6695, axiom:6696, prof:6698, volt:6699, blood:2517, c44:2523, dbow:2512, ovl:2501, mana:3004,
};

// ===== Mẫu hướng build: nhãn, độ ưu tiên chỉ số, kho đồ optional mặc định (theo thứ tự ưu tiên) =====
const PATH_TYPES = {
  mage:    { label:'Pháp sư dồn sát thương', aff:{AP:1,HASTE:.45,PEN:.35,MANA:.2,BURN:.2},
             pool:['rab','shad','vs','cry','storm','hor','bft','lud','zho','banshee','mal','morel'], boots:3020 },
  bmage:   { label:'Pháp sư thiêu đốt / đánh lâu', aff:{AP:.9,BURN:.8,HP:.35,HASTE:.3},
             pool:['rylai','bft','rift','cry','vs','rab','zho','morel','banshee','cos','blc'], boots:3020 },
  apburst: { label:'Sát thủ phép', aff:{AP:1,PEN:.5,MS:.3,SPELLBLADE:.3},
             pool:['shad','storm','rab','vs','cry','lud','zho','banshee','belt','lich'], boots:3020 },
  apas:    { label:'Phép thuật khi đánh trúng', aff:{AP:.8,AS:.8,ONHIT:1},
             pool:['guin','wit','rab','shad','vs','lich','statik','dd','rift','zho'], boots:3006 },
  adc:     { label:'Xạ thủ chí mạng', aff:{AD:.8,CRIT:1,AS:.7},
             pool:['ie','ldr','mr','bt','runaan','rfc','navori','pd','col','sbow','c44','dbow','yun'], boots:3006 },
  onhit:   { label:'Tốc đánh / khi đánh trúng', aff:{AS:1,ONHIT:1,AD:.4},
             pool:['guin','kraken','wit','term','runaan','bt','ldr','ster','dance','merc'], boots:3006 },
  leth:    { label:'Sát lực (xuyên giáp)', aff:{AD:1,PEN:1,HASTE:.35,MS:.2},
             pool:['col','axiom','sery','edge','opp','ghost','umb','serp','ldr','volt','dance'], boots:3158 },
  adcaster:{ label:'Vật lý kỹ năng (cấu rỉa)', aff:{AD:1,HASTE:.8,MANA:.3,SPELLBLADE:.4},
             pool:['sery','bc','shojin','reap','ecl','ldr','axiom','ie','sky','edge'], boots:3158 },
  bruiser: { label:'Đấu sĩ', aff:{AD:.8,HP:.6,HASTE:.5,SUST:.4,TEN:.2},
             pool:['ster','dance','maw','sery','titan','shojin','hex','chem','blood','ovl','jak','sv'], boots:3047 },
  tank:    { label:'Chống chịu', aff:{HP:1,AR:.8,MR:.8,BURN:.25},
             pool:['jak','thorn','fon','sv','ran','kaen','abyss','und','heart','warm','fh','dms','hol','sun'], boots:3047 },
  tanksup: { label:'Hỗ trợ đỡ đòn', aff:{HP:.8,AR:.6,MR:.6,HEALSH:.25,HASTE:.3},
             pool:['bandle','vow','jak','kaen','thorn','fon','abyss','und','hol','sun','ran','zeke','sol'], boots:3111 },
  aptank:  { label:'Chống chịu phép thuật (AP + Máu)', aff:{AP:.8,HP:.8,BURN:.4,HASTE:.3,AR:.2,MR:.2},
             pool:['rylai','hol','sun','cos','jak','abyss','blc','morel','fon','sv','zho','belt','rod'], boots:3047 },
  hpbruiser:{ label:'Đấu sĩ đỡ đòn (dồn Máu)', aff:{HP:1,AD:.5,AR:.3,MR:.3,SUST:.2},
             pool:['ster','sv','jak','thorn','fon','ran','kaen','dms','und','sky','maw'], boots:3047 },
  ench:    { label:'Hỗ trợ hồi máu / lá chắn', aff:{HEALSH:1,HASTE:.5,AP:.3,MANA:.2},
             pool:['red','mik','helia','dawn','cens','shur','sol','fwater','moon','arch'], boots:3158 },
};

// ===== Hồ sơ từng tướng: [loại, [đồ core...], (tùy chọn) {label, pool thêm, ghi chú}] =====
const B = {
  Aatrox:[['bruiser',['sky','bc']]],
  Ahri:[['apburst',['lud','shad']],['mage',['mal','lud'],{label:'Pháp sư cấu rỉa'}]],
  Akali:[['apburst',['lich','storm']],['bmage',['rift','zho'],{label:'Pháp sư đấu sĩ'}]],
  Akshan:[['adc',['col','ie']],['onhit',['kraken','botrk']]],
  Alistar:[['tanksup',['sol','zeke']],['tank',['sun','jak']],['aptank',['lia','rift']]],
  Ambessa:[['bruiser',['sky','bc']]],
  Amumu:[['tank',['sun','jak']],['bmage',['lia','rylai'],{label:'Phép thuật (AP)'}]],
  Anivia:[['bmage',['arch','rylai']],['mage',['lud','shad']]],
  Annie:[['mage',['lud','shad']],['bmage',['lia','rylai']]],
  Aphelios:[['adc',['yun','ie']]],
  Ashe:[['adc',['yun','ie']],['onhit',['botrk','kraken']]],
  AurelionSol:[['bmage',['rod','lia']],['mage',['lud','rab']]],
  Aurora:[['apburst',['lud','shad']],['bmage',['lia','rylai']]],
  Azir:[['apas',['nash','rift']],['mage',['lud','shad']]],
  Bard:[['ench',['shur','cens']],['apas',['nash','lich'],{label:'Phép thuật khi đánh trúng'}]],
  Belveth:[['onhit',['botrk','guin']],['bruiser',['sky','ster']]],
  Blitzcrank:[['tanksup',['sol','zeke']],['apburst',['lud','shad'],{label:'Phép thuật (AP)'}]],
  Brand:[['bmage',['lia','bft']],['mage',['lud','shad']]],
  Braum:[['tanksup',['sol','bandle']],['tank',['sun','jak']]],
  Briar:[['bruiser',['sky','bc']],['leth',['ecl','axiom']]],
  Caitlyn:[['adc',['col','ie']]],
  Camille:[['bruiser',['tri','sky']]],
  Cassiopeia:[['bmage',['rod','lia']],['mage',['arch','shad']],{note:'Cassiopeia không mua được giày.'}],
  Chogath:[['tank',['heart','sun']],['bmage',['rift','lia'],{label:'Phép thuật (AP)'}]],
  Corki:[['adc',['tri','ie'],{label:'Vật lý chí mạng'}],['mage',['lud','shad'],{label:'Phép thuật (AP)'}]],
  Darius:[['bruiser',['strid','ster']]],
  Diana:[['apburst',['lich','shad']],['bmage',['rift','zho'],{label:'Pháp sư đấu sĩ'}]],
  Draven:[['adc',['col','ie']]],
  DrMundo:[['tank',['heart','sv']]],
  Ekko:[['apburst',['lich','belt']],['bmage',['rift','lia']]],
  Elise:[['bmage',['lia','rift']],['apburst',['lud','shad']]],
  Evelynn:[['apburst',['lich','shad']]],
  Ezreal:[['adcaster',['mana','tri'],{label:'Vật lý (AD)'}],['mage',['lud','lich'],{label:'Phép thuật (AP)'}]],
  Fiddlesticks:[['bmage',['lia','zho']],['mage',['lud','shad']]],
  Fiora:[['bruiser',['rav','sky']]],
  Fizz:[['apburst',['lich','shad']],['bmage',['rift','zho']]],
  Galio:[['tank',['hol','abyss'],{label:'Chống chịu phép'}],['apburst',['lud','shad'],{label:'Phép thuật (AP)'}]],
  Gangplank:[['adcaster',['tri','navori'],{label:'Chí mạng kỹ năng'}],['leth',['col','axiom']]],
  Garen:[['bruiser',['strid','ster']],['adc',['navori','ie'],{label:'Chí mạng'}]],
  Gnar:[['bruiser',['tri','bc']],['tank',['sun','jak']]],
  Gragas:[['apburst',['belt','lud']],['tank',['hol','sun']]],
  Graves:[['adc',['col','navori']],['leth',['ecl','umb']]],
  Gwen:[['apas',['nash','rift']]],
  Hecarim:[['bruiser',['bc','sky']],['tank',['sun','jak']]],
  Heimerdinger:[['bmage',['lia','rylai']],['mage',['lud','shad']]],
  Hwei:[['mage',['lud','shad']],['bmage',['lia','rylai']]],
  Illaoi:[['bruiser',['bc','sky']]],
  Irelia:[['onhit',['botrk','sky']],['bruiser',['bc','ster']]],
  Ivern:[['ench',['moon','fwater']]],
  Janna:[['ench',['moon','fwater']],['mage',['lud','shad']]],
  JarvanIV:[['bruiser',['ecl','bc']],['tank',['sun','jak']]],
  Jax:[['bruiser',['tri','sky']],['apas',['nash','lich'],{label:'Phép thuật (AP)'}]],
  Jayce:[['adcaster',['mana','ecl']],['leth',['col','axiom']]],
  Jhin:[['adc',['col','ie']]],
  Jinx:[['adc',['yun','ie']]],
  Kaisa:[['onhit',['kraken','guin'],{label:'Vật lý khi đánh trúng'}],['apas',['nash','rab'],{label:'Phép thuật (AP)'}]],
  Kalista:[['onhit',['botrk','guin']]],
  Karma:[['mage',['lud','bft']],['ench',['moon','fwater']]],
  Karthus:[['bmage',['lia','bft']],['mage',['lud','rab']]],
  Kassadin:[['mage',['rod','lich']]],
  Katarina:[['apburst',['storm','shad']],['onhit',['botrk','guin'],{label:'Khi đánh trúng'}]],
  Kayle:[['apas',['nash','rab']]],
  Kayn:[['leth',['ecl','umb']],['bruiser',['sky','bc']]],
  Kennen:[['apburst',['storm','shad']],['bmage',['lia','zho']]],
  Khazix:[['leth',['ecl','umb']]],
  Kindred:[['onhit',['kraken','botrk']],['adc',['col','ie']]],
  Kled:[['bruiser',['bc','sky']]],
  KogMaw:[['onhit',['botrk','guin']],['mage',['lud','bft'],{label:'Phép thuật cấu rỉa'}]],
  KSante:[['tank',['bc','jak'],{label:'Đấu sĩ chống chịu'}]],
  Leblanc:[['apburst',['lud','shad']]],
  LeeSin:[['bruiser',['ecl','bc']],['tank',['sun','jak']]],
  Leona:[['tanksup',['sol','zeke']],['tank',['sun','jak']],['aptank',['lia','rift']]],
  Lillia:[['bmage',['lia','rylai']]],
  Lissandra:[['mage',['lud','mal']],['tank',['hol','abyss']]],
  Locke:[['apburst',['lud','shad']],['leth',['ecl','umb']],{note:'Tướng mới – nên đối chiếu thêm với build thực tế.'}],
  Lucian:[['adc',['reap','navori']],['leth',['ecl','umb']]],
  Lulu:[['ench',['moon','fwater']],['mage',['lud','shad']]],
  Lux:[['mage',['lud','shad']],['ench',['moon','imp'],{label:'Hỗ trợ khống chế'}]],
  Malphite:[['tank',['sun','thorn']],['apburst',['lud','shad'],{label:'Phép thuật (AP)'}]],
  Malzahar:[['bmage',['lia','mal']]],
  Maokai:[['bmage',['lia','bft'],{label:'Phép thuật (AP)'}],['tank',['sun','hol']]],
  MasterYi:[['onhit',['botrk','guin']],['adc',['yun','ie'],{label:'Chí mạng'}]],
  Mel:[['mage',['lud','shad']]],
  Milio:[['ench',['moon','fwater']]],
  MissFortune:[['leth',['col','opp']],['adc',['yun','ie'],{label:'Chí mạng'}]],
  MonkeyKing:[['bruiser',['bc','sky']],['tank',['sun','jak']]],
  Mordekaiser:[['bmage',['rift','lia']]],
  Morgana:[['bmage',['lia','zho']],['mage',['lud','shad']]],
  Naafiri:[['leth',['prof','ecl']]],
  Nami:[['ench',['moon','helia']]],
  Nasus:[['bruiser',['tri','bc']],['tank',['ghand','sun']]],
  Nautilus:[['tanksup',['sol','zeke']],['tank',['sun','jak']],['aptank',['lia','rift']]],
  Neeko:[['mage',['lud','shad']],['bmage',['lia','rylai']]],
  Nidalee:[['apburst',['lud','shad']]],
  Nilah:[['adc',['navori','ie']]],
  Nocturne:[['bruiser',['strid','bc']],['leth',['ecl','umb']]],
  Nunu:[['tank',['sun','hol']],['bmage',['lia','rylai'],{label:'Phép thuật (AP)'}]],
  Olaf:[['bruiser',['bc','sky']]],
  Orianna:[['mage',['lud','shad']]],
  Ornn:[['tank',['sun','jak']],['aptank',['lia','rift']]],
  Pantheon:[['leth',['ecl','umb']],['bruiser',['bc','sky']]],
  Poppy:[['tank',['sun','jak']],['bruiser',['bc','sky']]],
  Pyke:[['leth',['umb','ghost']]],
  Qiyana:[['leth',['prof','ecl']]],
  Quinn:[['leth',['col','ecl']],['adc',['yun','ie'],{label:'Chí mạng'}]],
  Rakan:[['ench',['shur','moon']],['tanksup',['sol','zeke']]],
  Rammus:[['tank',['thorn','sun']],['aptank',['lia','rift']]],
  RekSai:[['bruiser',['bc','sky']]],
  Rell:[['tanksup',['sol','zeke']],['tank',['sun','jak']],['aptank',['lia','rift']]],
  Renata:[['ench',['moon','helia']]],
  Renekton:[['bruiser',['bc','sky']]],
  Rengar:[['leth',['ecl','umb']],['bruiser',['bc','sky']]],
  Riven:[['bruiser',['prof','sky']]],
  Rumble:[['bmage',['lia','rift']]],
  Ryze:[['mage',['arch','rod']]],
  Samira:[['adc',['col','ie']]],
  Sejuani:[['tank',['sun','jak']],['aptank',['lia','rift']]],
  Senna:[['leth',['col','ecl']],['ench',['moon','helia']]],
  Seraphine:[['mage',['lud','bft']],['ench',['moon','helia']]],
  Sett:[['bruiser',['strid','sky']],['tank',['heart','sun']]],
  Shaco:[['leth',['ecl','umb']],['apburst',['lich','shad'],{label:'Phép thuật (AP)'}]],
  Shen:[['tank',['sun','jak']],['aptank',['lia','rift']]],
  Shyvana:[['bmage',['lia','rift'],{label:'Phép thuật (AP)'}],['onhit',['botrk','guin'],{label:'Vật lý khi đánh trúng'}]],
  Singed:[['bmage',['rylai','rift']],['tank',['sun','hol']]],
  Sion:[['tank',['heart','sun']],['bruiser',['bc','sky']]],
  Sivir:[['adc',['navori','ie']]],
  Skarner:[['tank',['sun','jak']],['aptank',['lia','rift']]],
  Smolder:[['adcaster',['reap','navori'],{label:'Chí mạng kỹ năng'}]],
  Sona:[['ench',['moon','helia']],['mage',['lud','shad']]],
  Soraka:[['ench',['moon','fwater']]],
  Swain:[['bmage',['lia','rift']]],
  Sylas:[['bmage',['rift','belt']],['apburst',['lud','shad']]],
  Syndra:[['mage',['lud','shad']]],
  TahmKench:[['tank',['heart','sun']],['aptank',['lia','rift']]],
  Taliyah:[['mage',['mal','lud']]],
  Talon:[['leth',['prof','ecl']]],
  Taric:[['tanksup',['sol','zeke']],['aptank',['lia','rift']]],
  Teemo:[['bmage',['lia','mal']],['apas',['nash','lia']]],
  Thresh:[['tanksup',['sol','zeke']],['aptank',['lia','rift']]],
  Tristana:[['adc',['col','ie']]],
  Trundle:[['bruiser',['bc','sky']],['tank',['sun','jak']]],
  Tryndamere:[['adc',['navori','ie']]],
  TwistedFate:[['mage',['lud','lich']],['apas',['nash','lich']]],
  Twitch:[['adc',['yun','ie']],['apas',['nash','rab'],{label:'Phép thuật (AP)'}]],
  Udyr:[['tank',['sun','jak']],['bruiser',['bc','sky']],['bmage',['rift','lia'],{label:'Phép thuật (AP)'}]],
  Urgot:[['bruiser',['bc','sky']]],
  Varus:[['leth',['col','ecl']],['onhit',['botrk','guin']],['mage',['bft','lud'],{label:'Phép thuật cấu rỉa'}]],
  Vayne:[['onhit',['botrk','guin']]],
  Veigar:[['mage',['lud','shad']]],
  Velkoz:[['mage',['lud','bft']]],
  Vex:[['mage',['lud','shad']]],
  Vi:[['bruiser',['bc','sky']]],
  Viego:[['onhit',['botrk','sky']]],
  Viktor:[['mage',['lud','shad']]],
  Vladimir:[['bmage',['rift','rab']]],
  Volibear:[['tank',['sun','jak']],['apas',['nash','rift'],{label:'Phép thuật (AP)'}]],
  Warwick:[['onhit',['botrk','sky']],['tank',['sun','jak']]],
  Xayah:[['adc',['yun','ie']]],
  Xerath:[['mage',['lud','bft']]],
  XinZhao:[['bruiser',['bc','sky']]],
  Yasuo:[['adc',['botrk','sbow'],{label:'Chí mạng + hút máu',pool:['ie','dance','ster','bt','wit','term','ldr','mr','kraken','maw','merc']}]],
  Yone:[['adc',['botrk','sbow'],{label:'Chí mạng + hút máu',pool:['ie','dance','ster','bt','wit','term','ldr','mr','kraken','maw','merc']}]],
  Yorick:[['bruiser',['bc','sky']]],
  Yunara:[['adc',['yun','ie']],['onhit',['botrk','guin']],{note:'Tướng mới – nên đối chiếu thêm với build thực tế.'}],
  Yuumi:[['ench',['moon','fwater']]],
  Zaahen:[['bruiser',['bc','sky']],{note:'Tướng mới – nên đối chiếu thêm với build thực tế.'}],
  Zac:[['tank',['sun','jak']],['bmage',['lia','rift'],{label:'Phép thuật (AP)'}]],
  Zed:[['leth',['prof','ecl']]],
  Zeri:[['adc',['yun','ie']]],
  Ziggs:[['mage',['lud','bft']]],
  Zilean:[['mage',['lud','bft']],['ench',['moon','shur']]],
  Zoe:[['mage',['lud','shad']]],
  Zyra:[['bmage',['lia','bft']]],
};

// ===== Build phổ biến trong Hỗn Loạn: Đấu sĩ đỡ đòn dồn Máu =====
// Trái Tim Khổng Thần + Huyết Giáp Chúa Tể + Rìu Đại Mãng Xà + Giáp Máu Warmog + đồ tình huống
const HP_BRUISER_CORE = ['heart','ovl','titan','warm'];
// Chỉ tướng đấu sĩ cận chiến đánh thường nhiều (Rìu Đại Mãng Xà, Trái Tim Khổng Thần kích hoạt qua đòn đánh)
const HP_BRUISER = ['Sett','Darius','Garen','DrMundo','Volibear','Trundle','Olaf','Udyr','Warwick','Renekton','Yorick','Urgot',
  'Vi','XinZhao','MonkeyKing','RekSai','Kled','Briar','Jax','Nocturne','Shyvana','Belveth','Sion','Shen'];

// ===== Chỉnh sửa theo từng tướng (theo góp ý người chơi) =====
// removeLabels: bỏ tab có đúng tên này; add: thêm build phổ biến cố định (2 món đầu là Core, các món sau xếp đúng thứ tự ở ô Optional)
const OVERRIDES = {
  Trundle: {
    removeLabels: ['Chống chịu'],
    add: [{ type: 'bmage', label: 'Phép thuật khống chế (AP)', items: ['imp','rylai','lia','bft','shad','rab'], extra: ['zho','vs','cry','morel','rift'], boots: 3020,
      why: 'Build phép thuật thịnh hành của Trundle trong Hỗn Loạn: Trát Lệnh Đế Vương + Trượng Pha Lê Rylai giữ chân và đánh dấu mục tiêu, Mặt Nạ Đọa Đày Liandry + Đuốc Lửa Đen thiêu đốt liên tục, Ngọn Lửa Hắc Hóa và Mũ Phù Thủy Rabadon dồn sát thương.' }],
  },
};
